### ISSUE TITLE
Searches that fail give an Internal Server Error

### ISSUE THREAD

**Issue by dkensiski** [vmoa/imagelib#2]
Reported by: George Loyer

Entering a search term that does not return any results returns an Internal Server Error rather than a search results page that reports No Matches or some other indication that the search was successful but that there were no results that matched.

**Comment by dkensiski** [comment]
Tagging @georgeloyer so he will (hopefully) receive updates.

**Comment by dkensiski** [comment]
Traceback (most recent call last):
```
  File "/Users/dkensiski/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/dkensiski/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/dkensiski/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkensiski/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkensiski/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkensiski/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/dkensiski/Documents/Kensiski/RFO/src/imagelib/__init__.py", line 40, in top
    t = markup.build_images(start = flask.request.form.get('start'),
  File "/Users/dkensiski/Documents/Kensiski/RFO/src/imagelib/./markup.py", line 69, in build_images
    images["date"] = dates[startX]
IndexError: list index out of range
```

**Comment by dkensiski** [comment]
I have posted an interim fix that addresses the reported error -- if you query an unknown target it will display an error rather than crash the server.  But in testing that it exposed a similar failure if you search two unknown targets in a row.  I'll work on that tomorrow.

**Comment by georgeloyer** [comment]
Confirmed fixed and the new behavior is helpful, keeping the previous search result on the page while messaging, in red, that the search term did not return a result.  I am not able to reproduce the behavior that two searches for unknown targets in a row fails with an internal server error.  It looks like that might be fixed.

**Comment by georgeloyer** [comment]
Confirmed that the fix is complete with Dave K
